### ISSUE TITLE
vulnerabilities

### ISSUE THREAD

**Issue by ranshe** [ARMmbed/mbed-connector-api-node-quickstart#10]
_npm install
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN mbed-connector-node-quickstart@2.0.0 No license field.

added 159 packages from 149 contributors and audited 295 packages in 5.263s
found 13 vulnerabilities (10 low, 3 high)
  run `npm audit fix` to fix them, or `npm audit` for details_

Need to use npm audit fix --force to get rid of this

**Comment by BlackstoneEngineering** [comment]
this will not be fixed as this repo is no longer maintained (its from the connector days ran, it shouldnt work with the latest pelion dms )

**Comment by ranshe** [comment]
It actually still works - tested last week.
I think we should keep open - if this is ever resurrected, we need to know where we stood (but it's not that high on my priority list)
